// Mock seed inlined from docs/reference Step 6 v2 MOCK_DATA_SEED.json.
// Per project rule "do not copy external folders into the app", the data is
// re-stated here as typed TS constants instead of being imported at runtime.
// Replace with a real backend / DB read when the catalog API is live.

import type { Brand, PriceRecord, Trim } from "./types";

export const BRANDS: readonly Brand[] = [
  { brand_id: "brand_byd", name: "BYD", country: "China", status: "active" },
  { brand_id: "brand_volvo", name: "Volvo", country: "Sweden", status: "active" },
  { brand_id: "brand_toyota", name: "Toyota", country: "Japan", status: "active" },
  { brand_id: "brand_li_auto", name: "Li Auto", country: "China", status: "active" },
  { brand_id: "brand_kia", name: "Kia", country: "Korea", status: "active" },
  { brand_id: "brand_hyundai", name: "Hyundai", country: "Korea", status: "active" },
  { brand_id: "brand_hongqi", name: "Hongqi", country: "China", status: "active" },
];

export const TRIMS: readonly Trim[] = [
  {
    trim_id: "trim_byd_han_ev_premium_awd_2025",
    brand_id: "brand_byd",
    model_name: "Han",
    year: 2025,
    display_name: "BYD Han EV Premium AWD",
    energy_type: "EV",
    body_type: "sedan",
    power_hp: 510,
    range_km: 610,
    status: "active",
  },
  {
    trim_id: "trim_volvo_xc60_t8_recharge_plus_2025",
    brand_id: "brand_volvo",
    model_name: "XC60",
    year: 2025,
    display_name: "Volvo XC60 T8 Recharge Plus",
    energy_type: "PHEV",
    body_type: "suv",
    generation_id: "gen_volvo_xc60_ii",
    power_hp: 455,
    range_km: 78,
    status: "active",
  },
  {
    trim_id: "trim_toyota_camry_25_hybrid_prestige_2025",
    brand_id: "brand_toyota",
    model_name: "Camry",
    year: 2025,
    display_name: "Toyota Camry 2.5 Hybrid Prestige",
    energy_type: "HEV",
    body_type: "sedan",
    generation_id: "gen_toyota_camry_xv80",
    power_hp: 225,
    range_km: null,
    status: "active",
  },
  {
    trim_id: "trim_li_auto_l9_max_erev_6seat_2025",
    brand_id: "brand_li_auto",
    model_name: "L9",
    year: 2025,
    display_name: "Li Auto L9 Max EREV 6-seat",
    energy_type: "EREV",
    body_type: "suv",
    power_hp: 449,
    range_km: 1315,
    status: "active",
  },
  {
    trim_id: "trim_kia_ev6_gt_line_awd_2025",
    brand_id: "brand_kia",
    model_name: "EV6",
    year: 2025,
    display_name: "Kia EV6 GT-Line AWD",
    energy_type: "EV",
    body_type: "crossover",
    generation_id: "gen_kia_ev6_g1",
    power_hp: 320,
    range_km: 506,
    status: "active",
  },
  {
    trim_id: "trim_hyundai_tucson_16_tgdi_2025",
    brand_id: "brand_hyundai",
    model_name: "Tucson",
    year: 2025,
    display_name: "Hyundai Tucson 1.6 T-GDI",
    energy_type: "ICE",
    body_type: "suv",
    generation_id: "gen_hyundai_tucson_nx4",
    power_hp: 180,
    range_km: null,
    status: "active",
  },
  {
    trim_id: "trim_byd_seal_ev_long_range_2025",
    brand_id: "brand_byd",
    model_name: "Seal",
    year: 2025,
    display_name: "BYD Seal EV Long Range",
    energy_type: "EV",
    body_type: "sedan",
    power_hp: 313,
    range_km: 700,
    status: "active",
  },
  {
    trim_id: "trim_hongqi_ehs9_ev_6year_2025",
    brand_id: "brand_hongqi",
    model_name: "E-HS9",
    year: 2025,
    display_name: "Hongqi E-HS9 EV 6-year",
    energy_type: "EV",
    body_type: "suv",
    power_hp: 551,
    range_km: 510,
    status: "active",
  },
  // Sprint 10F: 12 additional komplektasiya added for the local demo review
  // (Section A target: 20 trims). New trims reference generations from
  // lib/cars/generations.ts where appropriate. Inline power_hp / range_km
  // fields serve as the advanced spec set (Section A target: 10 trims with
  // advanced specs — every trim above and below now carries both).
  {
    trim_id: "trim_byd_song_plus_dmi_2025",
    brand_id: "brand_byd",
    model_name: "Song Plus",
    year: 2025,
    display_name: "BYD Song Plus DM-i Champion",
    energy_type: "PHEV",
    body_type: "suv",
    generation_id: "gen_byd_song_plus_2",
    power_hp: 197,
    range_km: 110,
    status: "active",
  },
  {
    trim_id: "trim_byd_tang_ev_premium_awd_2025",
    brand_id: "brand_byd",
    model_name: "Tang",
    year: 2025,
    display_name: "BYD Tang EV Premium AWD",
    energy_type: "EV",
    body_type: "suv",
    generation_id: "gen_byd_tang_3",
    power_hp: 517,
    range_km: 530,
    status: "active",
  },
  {
    trim_id: "trim_byd_seal_performance_awd_2025",
    brand_id: "brand_byd",
    model_name: "Seal",
    year: 2025,
    display_name: "BYD Seal Performance AWD",
    energy_type: "EV",
    body_type: "sedan",
    power_hp: 530,
    range_km: 520,
    status: "active",
  },
  {
    trim_id: "trim_toyota_rav4_25_hybrid_xse_2025",
    brand_id: "brand_toyota",
    model_name: "RAV4",
    year: 2025,
    display_name: "Toyota RAV4 2.5 Hybrid XSE AWD",
    energy_type: "HEV",
    body_type: "suv",
    generation_id: "gen_toyota_rav4_xa50",
    power_hp: 222,
    range_km: null,
    status: "active",
  },
  {
    trim_id: "trim_toyota_corolla_15_hybrid_2025",
    brand_id: "brand_toyota",
    model_name: "Corolla",
    year: 2025,
    display_name: "Toyota Corolla 1.8 Hybrid",
    energy_type: "HEV",
    body_type: "sedan",
    power_hp: 140,
    range_km: null,
    status: "active",
  },
  {
    trim_id: "trim_toyota_camry_25_hybrid_premium_2025",
    brand_id: "brand_toyota",
    model_name: "Camry",
    year: 2025,
    display_name: "Toyota Camry 2.5 Hybrid Premium",
    energy_type: "HEV",
    body_type: "sedan",
    generation_id: "gen_toyota_camry_xv80",
    power_hp: 232,
    range_km: null,
    status: "active",
  },
  {
    trim_id: "trim_volvo_xc40_recharge_twin_2025",
    brand_id: "brand_volvo",
    model_name: "XC40",
    year: 2025,
    display_name: "Volvo XC40 Recharge Twin AWD",
    energy_type: "EV",
    body_type: "crossover",
    generation_id: "gen_volvo_xc40_1",
    power_hp: 408,
    range_km: 460,
    status: "active",
  },
  {
    trim_id: "trim_volvo_s60_t8_polestar_2025",
    brand_id: "brand_volvo",
    model_name: "S60",
    year: 2025,
    display_name: "Volvo S60 T8 Polestar Engineered",
    energy_type: "PHEV",
    body_type: "sedan",
    generation_id: "gen_volvo_s60_iii",
    power_hp: 455,
    range_km: 90,
    status: "active",
  },
  {
    trim_id: "trim_kia_sorento_25_signature_2025",
    brand_id: "brand_kia",
    model_name: "Sorento",
    year: 2025,
    display_name: "Kia Sorento 2.5 T-GDI Signature AWD",
    energy_type: "ICE",
    body_type: "suv",
    power_hp: 281,
    range_km: null,
    status: "active",
  },
  {
    trim_id: "trim_hyundai_ioniq5_long_range_awd_2025",
    brand_id: "brand_hyundai",
    model_name: "Ioniq 5",
    year: 2025,
    display_name: "Hyundai Ioniq 5 Long Range AWD",
    energy_type: "EV",
    body_type: "crossover",
    generation_id: "gen_hyundai_ioniq5_ne",
    power_hp: 325,
    range_km: 481,
    status: "active",
  },
  {
    trim_id: "trim_hyundai_tucson_hybrid_n_line_2025",
    brand_id: "brand_hyundai",
    model_name: "Tucson",
    year: 2025,
    display_name: "Hyundai Tucson Hybrid N Line AWD",
    energy_type: "HEV",
    body_type: "suv",
    generation_id: "gen_hyundai_tucson_nx4",
    power_hp: 230,
    range_km: null,
    status: "active",
  },
  {
    trim_id: "trim_li_auto_l7_max_erev_2025",
    brand_id: "brand_li_auto",
    model_name: "L7",
    year: 2025,
    display_name: "Li Auto L7 Max EREV",
    energy_type: "EREV",
    body_type: "suv",
    power_hp: 449,
    range_km: 1315,
    status: "active",
  },
];

// Dealer-offer rows from the seed, surfaced as PriceRecord items.
export const DEALER_OFFERS: readonly PriceRecord[] = [
  {
    offer_id: "offer_001",
    dealer_id: "dealer_premium_auto_baku",
    trim_id: "trim_byd_han_ev_premium_awd_2025",
    amount: 89500,
    currency: "AZN",
    status: "dealer_official_offer",
    stock_status: "available",
    source_type: "official_dealer",
    source_name: "Premium Auto Baku",
    verification_status: "verified",
    last_updated: "2026-05-04T10:00:00+04:00",
    valid_from: "2026-05-04T10:00:00+04:00",
    valid_until: "2026-05-07T23:59:00+04:00",
    included_fees: ["ƏDV", "DYP", "Bakı təhvil"],
    excluded_fees: [],
    signed_pdf_url: null,
  },
  {
    offer_id: "offer_002",
    dealer_id: "dealer_nordic_motors_azerbaijan",
    trim_id: "trim_volvo_xc60_t8_recharge_plus_2025",
    amount: 101200,
    currency: "AZN",
    status: "dealer_official_offer",
    stock_status: "order",
    source_type: "official_dealer",
    source_name: "Nordic Motors Azerbaijan",
    verification_status: "verified",
    last_updated: "2026-05-03T10:00:00+04:00",
    valid_from: "2026-05-03T10:00:00+04:00",
    valid_until: "2026-05-12T23:59:00+04:00",
    included_fees: ["ƏDV", "DYP"],
    excluded_fees: ["Sığorta"],
    signed_pdf_url: null,
  },
  {
    offer_id: "offer_003",
    dealer_id: "dealer_caspian_auto_group",
    trim_id: "trim_toyota_camry_25_hybrid_prestige_2025",
    amount: 71200,
    currency: "AZN",
    status: "catalog_price",
    stock_status: "available",
    source_type: "partner",
    source_name: "Caspian Auto Group",
    verification_status: "pending",
    last_updated: "2026-05-01T10:00:00+04:00",
    valid_from: "2026-05-01T10:00:00+04:00",
    valid_until: "2026-05-20T23:59:00+04:00",
    included_fees: ["ƏDV"],
    excluded_fees: ["DYP"],
    signed_pdf_url: null,
  },
  {
    offer_id: "offer_004",
    dealer_id: "dealer_premium_auto_baku",
    trim_id: "trim_byd_seal_ev_long_range_2025",
    amount: 67400,
    currency: "AZN",
    status: "dealer_official_offer",
    stock_status: "available",
    source_type: "official_dealer",
    source_name: "Premium Auto Baku",
    verification_status: "verified",
    last_updated: "2026-05-04T10:00:00+04:00",
    valid_from: "2026-05-04T10:00:00+04:00",
    valid_until: "2026-05-07T23:59:00+04:00",
    included_fees: ["ƏDV", "DYP"],
    excluded_fees: [],
    signed_pdf_url: null,
  },
  {
    offer_id: "offer_005",
    dealer_id: "dealer_premium_auto_baku",
    trim_id: "trim_hongqi_ehs9_ev_6year_2025",
    amount: 168900,
    currency: "AZN",
    status: "dealer_quote_pending",
    stock_status: "order",
    source_type: "official_dealer",
    source_name: "Premium Auto Baku",
    verification_status: "pending",
    last_updated: "2026-05-04T10:00:00+04:00",
    valid_from: "2026-05-04T10:00:00+04:00",
    valid_until: "2026-05-14T23:59:00+04:00",
    included_fees: [],
    excluded_fees: [],
    signed_pdf_url: null,
  },
  {
    offer_id: "offer_006",
    dealer_id: "dealer_caspian_auto_group",
    trim_id: "trim_kia_ev6_gt_line_awd_2025",
    amount: 0,
    currency: "AZN",
    status: "price_unknown",
    stock_status: "coming_soon",
    source_type: "partner",
    source_name: "Caspian Auto Group",
    verification_status: "pending",
    last_updated: "2026-05-05T10:00:00+04:00",
    valid_from: "2026-05-05T10:00:00+04:00",
    valid_until: null,
    included_fees: [],
    excluded_fees: [],
    signed_pdf_url: null,
  },
];

// SPRINT_2_DEMO_FIXTURE — supplements the 4 PriceStatus values absent from the
// seed (estimated, expired_offer, conflict, not_available) so the PriceCard
// component (Batch 2.3) can be exercised against all 8 states. Replace with
// real catalog/offer data when backend is live.
export const EXTRA_PRICES: readonly PriceRecord[] = [
  // estimated — Zolaq aggregator estimate, no dealer attached
  {
    trim_id: "trim_li_auto_l9_max_erev_6seat_2025",
    amount: 145000,
    currency: "AZN",
    status: "estimated",
    source_type: "estimate",
    source_name: "Zolaq qiymət təxmini",
    verification_status: "unverified",
    last_updated: "2026-05-10T08:00:00+04:00",
  },
  // expired_offer — past valid_until
  {
    trim_id: "trim_hyundai_tucson_16_tgdi_2025",
    amount: 52500,
    currency: "AZN",
    status: "expired_offer",
    source_type: "partner",
    source_name: "Caspian Auto Group",
    verification_status: "outdated",
    last_updated: "2026-04-01T10:00:00+04:00",
    dealer_id: "dealer_caspian_auto_group",
    stock_status: "available",
    valid_from: "2026-04-01T10:00:00+04:00",
    valid_until: "2026-04-15T23:59:00+04:00",
    included_fees: ["ƏDV"],
    excluded_fees: ["DYP"],
    signed_pdf_url: null,
  },
  // conflict — catalog source disagrees with offer_006's price_unknown
  {
    trim_id: "trim_kia_ev6_gt_line_awd_2025",
    amount: 78900,
    currency: "AZN",
    status: "conflict",
    source_type: "catalog",
    source_name: "Zolaq kataloqu",
    verification_status: "conflict",
    last_updated: "2026-05-08T09:00:00+04:00",
  },
  // not_available — out of stock notice
  {
    trim_id: "trim_hyundai_tucson_16_tgdi_2025",
    amount: 0,
    currency: "AZN",
    status: "not_available",
    source_type: "zolaq_manual",
    source_name: "Zolaq",
    verification_status: "verified",
    last_updated: "2026-05-10T09:00:00+04:00",
  },
  // Sprint 10F: catalog reference prices for the new komplektasiya so the
  // public price card and admin /catalog/prices list reflect realistic data.
  {
    trim_id: "trim_byd_song_plus_dmi_2025",
    amount: 41900,
    currency: "AZN",
    status: "catalog_price",
    source_type: "catalog",
    source_name: "Zolaq kataloqu",
    verification_status: "verified",
    last_updated: "2026-05-12T09:00:00+04:00",
  },
  {
    trim_id: "trim_hyundai_ioniq5_long_range_awd_2025",
    amount: 88500,
    currency: "AZN",
    status: "catalog_price",
    source_type: "catalog",
    source_name: "Zolaq kataloqu",
    verification_status: "verified",
    last_updated: "2026-05-12T09:00:00+04:00",
  },
];
