// Initial ad-request rows covering the main status states so the admin and
// dealer UIs render something useful on first boot.

import type { AdRequest } from "./types";

export const AD_REQUEST_SEED: readonly AdRequest[] = [
  {
    ad_request_id: "adr_seed_1",
    dealer_id: "dealer_premium_auto_baku",
    initiated_by: "dealer",
    submitted_by: "Premium Auto Sales",
    package_type: "featured_offer",
    placement: "catalog",
    label: "Sponsorlu",
    status: "submitted",
    campaign_note: "BYD Song Plus üçün önə çıxan kataloq mövqeyi.",
    start_date: "2026-05-20",
    end_date: "2026-06-20",
    created_at: Date.parse("2026-05-12T09:00:00+04:00"),
    updated_at: Date.parse("2026-05-12T09:00:00+04:00"),
  },
  {
    ad_request_id: "adr_seed_2",
    dealer_id: "dealer_nordic_motors_azerbaijan",
    initiated_by: "dealer",
    submitted_by: "Nordic Sales",
    package_type: "premium_dealer_profile",
    placement: "dealer_list",
    label: "Premium",
    status: "invoice_sent",
    campaign_note: "Volvo aylıq premium profil.",
    start_date: "2026-06-01",
    end_date: "2026-06-30",
    invoice_id: "inv_seed_1",
    created_at: Date.parse("2026-05-08T10:00:00+04:00"),
    updated_at: Date.parse("2026-05-13T11:00:00+04:00"),
  },
  {
    ad_request_id: "adr_seed_3",
    dealer_id: "dealer_premium_auto_baku",
    initiated_by: "dealer",
    submitted_by: "Premium Auto Sales",
    package_type: "homepage_sponsored_block",
    placement: "homepage",
    label: "Reklam",
    status: "active",
    campaign_note: "Yaz endirim kampaniyası.",
    start_date: "2026-05-01",
    end_date: "2026-05-31",
    invoice_id: "inv_seed_2",
    activated_at: Date.parse("2026-05-02T08:00:00+04:00"),
    activated_by: "admin_ops",
    created_at: Date.parse("2026-04-20T09:00:00+04:00"),
    updated_at: Date.parse("2026-05-02T08:00:00+04:00"),
  },
  {
    ad_request_id: "adr_seed_4",
    dealer_id: null,
    initiated_by: "admin",
    submitted_by: "Master Admin",
    package_type: "content_sponsorship",
    placement: "news_detail",
    label: "Sponsorlu",
    status: "draft",
    campaign_note: "Daxili: EV xəbərləri üçün sponsorluq yer rezervi.",
    created_at: Date.parse("2026-05-13T15:00:00+04:00"),
    updated_at: Date.parse("2026-05-13T15:00:00+04:00"),
  },
  {
    ad_request_id: "adr_seed_5",
    dealer_id: "dealer_nordic_motors_azerbaijan",
    initiated_by: "dealer",
    submitted_by: "Nordic Sales",
    package_type: "featured_dealer_placement",
    placement: "dealer_detail",
    label: null,
    status: "rejected",
    campaign_note: "Volvo XC40 önə çıxarma.",
    rejection_reason: "Yerləşdirmə davaları əldə olunub, gələn ay yenidən yoxlanılsın.",
    created_at: Date.parse("2026-04-25T12:00:00+04:00"),
    updated_at: Date.parse("2026-04-26T09:00:00+04:00"),
  },
];
